services:
  gateway-service:
    build:
      context: .
      dockerfile: deploy/gateway.Dockerfile
    container_name: gateway
    env_file:
      - .env
    networks:
      - flyte-network
    depends_on:
      - user-service
      - flight-service
    ports:
      - "${GATEWAY_HTTP_PORT}:8080"

  user-db:
    image: postgres:15-alpine
    container_name: user-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    networks:
      - flyte-network
    ports:
      - "${USER_DB_PORT_EXTERNAL}:5432"
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: deploy/user.Dockerfile
    container_name: user-service
    env_file:
      - .env
    networks:
      - flyte-network
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - "${USER_GRPC_PORT}:${USER_GRPC_PORT}"

  flight-db:
    image: postgres:15-alpine
    container_name: flight-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${FLIGHT_DB_USER}
      POSTGRES_PASSWORD: ${FLIGHT_DB_PASSWORD}
      POSTGRES_DB: ${FLIGHT_DB_NAME}
    networks:
      - flyte-network
    ports:
      - "${FLIGHT_DB_PORT_EXTERNAL}:5432"
    volumes:
      - flight_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${FLIGHT_DB_USER} -d ${FLIGHT_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - flyte-network
    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flight-service:
    build:
      context: .
      dockerfile: deploy/flight.Dockerfile
    container_name: flight-service
    env_file:
      - .env
    networks:
      - flyte-network
    depends_on:
      flight-db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "${FLIGHT_GRPC_PORT}:${FLIGHT_GRPC_PORT}"

  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
      POSTGRES_DB: ${PAYMENT_DB_NAME}
    networks:
      - flyte-network
    ports:
      - "${PAYMENT_DB_PORT_EXTERNAL}:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PAYMENT_DB_USER} -d ${PAYMENT_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - flyte-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - flyte-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  payment-service:
    build:
      context: .
      dockerfile: deploy/payment.Dockerfile
    container_name: payment-service
    env_file:
      - .env
    environment:
      KAFKA_BROKERS: kafka:9092
    networks:
      - flyte-network
    depends_on:
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  booking-db:
    image: postgres:15-alpine
    container_name: booking-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${BOOKING_DB_USER}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASSWORD}
      POSTGRES_DB: ${BOOKING_DB_NAME}
    networks:
      - flyte-network
    ports:
      - "${BOOKING_DB_PORT_EXTERNAL}:5432"
    volumes:
      - booking_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${BOOKING_DB_USER} -d ${BOOKING_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  booking-service:
    build:
      context: .
      dockerfile: deploy/booking.Dockerfile
    container_name: booking-service
    env_file:
      - .env
    networks:
      - flyte-network
    depends_on:
      booking-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      flight-service:
        condition: service_started
    ports:
      - "${BOOKING_GRPC_PORT}:${BOOKING_GRPC_PORT}"

  frontend:
    build:
      context: .
      dockerfile: deploy/frontend.Dockerfile
    container_name: frontend
    env_file:
      - .env
    networks:
      - flyte-network
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  user_pg_data:
  flight_pg_data:
  payment_pg_data:
  booking_pg_data:
  es_data:

networks:
  flyte-network:
    driver: bridge